// Code generated by protoc-gen-go.
// source: golang.conradwood.net/apis/framework/framework.proto
// DO NOT EDIT!

/*
Package framework is a generated protocol buffer package.

It is generated from these files:
	golang.conradwood.net/apis/framework/framework.proto

It has these top-level messages:
	DEPRECATED_CallTrace
	DEPRECATED_FrameworkMessageDetail
*/
package framework

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// deprecated
type DEPRECATED_CallTrace struct {
	Service string `protobuf:"bytes,1,opt,name=Service" json:"Service,omitempty"`
	Method  string `protobuf:"bytes,2,opt,name=Method" json:"Method,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
}

func (m *DEPRECATED_CallTrace) Reset()                    { *m = DEPRECATED_CallTrace{} }
func (m *DEPRECATED_CallTrace) String() string            { return proto.CompactTextString(m) }
func (*DEPRECATED_CallTrace) ProtoMessage()               {}
func (*DEPRECATED_CallTrace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DEPRECATED_CallTrace) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *DEPRECATED_CallTrace) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *DEPRECATED_CallTrace) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// deprecated
type DEPRECATED_FrameworkMessageDetail struct {
	CallTraces []*DEPRECATED_CallTrace `protobuf:"bytes,1,rep,name=CallTraces" json:"CallTraces,omitempty"`
	Message    string                  `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	RequestID  string                  `protobuf:"bytes,3,opt,name=RequestID" json:"RequestID,omitempty"`
}

func (m *DEPRECATED_FrameworkMessageDetail) Reset()         { *m = DEPRECATED_FrameworkMessageDetail{} }
func (m *DEPRECATED_FrameworkMessageDetail) String() string { return proto.CompactTextString(m) }
func (*DEPRECATED_FrameworkMessageDetail) ProtoMessage()    {}
func (*DEPRECATED_FrameworkMessageDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

func (m *DEPRECATED_FrameworkMessageDetail) GetCallTraces() []*DEPRECATED_CallTrace {
	if m != nil {
		return m.CallTraces
	}
	return nil
}

func (m *DEPRECATED_FrameworkMessageDetail) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DEPRECATED_FrameworkMessageDetail) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func init() {
	proto.RegisterType((*DEPRECATED_CallTrace)(nil), "framework.DEPRECATED_CallTrace")
	proto.RegisterType((*DEPRECATED_FrameworkMessageDetail)(nil), "framework.DEPRECATED_FrameworkMessageDetail")
}

func init() {
	proto.RegisterFile("golang.conradwood.net/apis/framework/framework.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x32, 0x49, 0xcf, 0xcf, 0x49,
	0xcc, 0x4b, 0xd7, 0x4b, 0xce, 0xcf, 0x2b, 0x4a, 0x4c, 0x29, 0xcf, 0xcf, 0x4f, 0xd1, 0xcb, 0x4b,
	0x2d, 0xd1, 0x4f, 0x2c, 0xc8, 0x2c, 0xd6, 0x4f, 0x2b, 0x4a, 0xcc, 0x4d, 0x2d, 0xcf, 0x2f, 0xca,
	0x46, 0xb0, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x38, 0xe1, 0x02, 0x4a, 0x49, 0x5c, 0x22,
	0x2e, 0xae, 0x01, 0x41, 0xae, 0xce, 0x8e, 0x21, 0xae, 0x2e, 0xf1, 0xce, 0x89, 0x39, 0x39, 0x21,
	0x45, 0x89, 0xc9, 0xa9, 0x42, 0x12, 0x5c, 0xec, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x30, 0xae, 0x90, 0x18, 0x17, 0x9b, 0x6f, 0x6a, 0x49, 0x46,
	0x7e, 0x8a, 0x04, 0x13, 0x58, 0x02, 0xca, 0x03, 0xe9, 0xf0, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f,
	0x95, 0x60, 0x86, 0xe8, 0x80, 0x72, 0x95, 0xe6, 0x30, 0x72, 0x29, 0x22, 0x59, 0xe2, 0x06, 0xb3,
	0x1c, 0x2a, 0xef, 0x92, 0x5a, 0x92, 0x98, 0x99, 0x23, 0x64, 0xcf, 0xc5, 0x05, 0xb7, 0xbe, 0x58,
	0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x5e, 0x0f, 0xe1, 0x74, 0x6c, 0xce, 0x0c, 0x42, 0xd2,
	0x82, 0xec, 0x00, 0x26, 0x14, 0x07, 0x08, 0xc9, 0x70, 0x71, 0x06, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x78, 0xba, 0x40, 0x1d, 0x87, 0x10, 0x70, 0x72, 0xe7, 0x92, 0xc7, 0x1a, 0x8a, 0x08, 0xbb,
	0xa3, 0x54, 0x88, 0x09, 0xe6, 0x24, 0x36, 0x70, 0xe8, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x37, 0xe2, 0x2c, 0x88, 0x95, 0x01, 0x00, 0x00,
}
