// Code generated by protoc-gen-go.
// source: protos/golang.conradwood.net/apis/framework/framework.proto
// DO NOT EDIT!

/*
Package framework is a generated protocol buffer package.

It is generated from these files:
	protos/golang.conradwood.net/apis/framework/framework.proto

It has these top-level messages:
	CallTrace
	FrameworkMessageDetail
	InContext
	ImmutableContext
	MutableContext
*/
package framework

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import auth "golang.conradwood.net/apis/auth"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CallTrace struct {
	Service string `protobuf:"bytes,1,opt,name=Service" json:"Service,omitempty"`
	Method  string `protobuf:"bytes,2,opt,name=Method" json:"Method,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
}

func (m *CallTrace) Reset()                    { *m = CallTrace{} }
func (m *CallTrace) String() string            { return proto.CompactTextString(m) }
func (*CallTrace) ProtoMessage()               {}
func (*CallTrace) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CallTrace) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *CallTrace) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *CallTrace) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FrameworkMessageDetail struct {
	CallTraces []*CallTrace `protobuf:"bytes,1,rep,name=CallTraces" json:"CallTraces,omitempty"`
	Message    string       `protobuf:"bytes,2,opt,name=Message" json:"Message,omitempty"`
	RequestID  string       `protobuf:"bytes,3,opt,name=RequestID" json:"RequestID,omitempty"`
}

func (m *FrameworkMessageDetail) Reset()                    { *m = FrameworkMessageDetail{} }
func (m *FrameworkMessageDetail) String() string            { return proto.CompactTextString(m) }
func (*FrameworkMessageDetail) ProtoMessage()               {}
func (*FrameworkMessageDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FrameworkMessageDetail) GetCallTraces() []*CallTrace {
	if m != nil {
		return m.CallTraces
	}
	return nil
}

func (m *FrameworkMessageDetail) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *FrameworkMessageDetail) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

// this is transported within the Context of a call
type InContext struct {
	ImCtx *ImmutableContext `protobuf:"bytes,1,opt,name=ImCtx" json:"ImCtx,omitempty"`
	MCtx  *MutableContext   `protobuf:"bytes,2,opt,name=MCtx" json:"MCtx,omitempty"`
}

func (m *InContext) Reset()                    { *m = InContext{} }
func (m *InContext) String() string            { return proto.CompactTextString(m) }
func (*InContext) ProtoMessage()               {}
func (*InContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InContext) GetImCtx() *ImmutableContext {
	if m != nil {
		return m.ImCtx
	}
	return nil
}

func (m *InContext) GetMCtx() *MutableContext {
	if m != nil {
		return m.MCtx
	}
	return nil
}

// this must not be changed throughout its lifetime. furthermore, go-easyops _must_ transport this as-is (preserving unknown fields)
type ImmutableContext struct {
	RequestID      string              `protobuf:"bytes,1,opt,name=RequestID" json:"RequestID,omitempty"`
	CreatorService *auth.SignedUser    `protobuf:"bytes,2,opt,name=CreatorService" json:"CreatorService,omitempty"`
	User           *auth.SignedUser    `protobuf:"bytes,3,opt,name=User" json:"User,omitempty"`
	SudoUser       *auth.SignedUser    `protobuf:"bytes,4,opt,name=SudoUser" json:"SudoUser,omitempty"`
	Session        *auth.SignedSession `protobuf:"bytes,5,opt,name=Session" json:"Session,omitempty"`
}

func (m *ImmutableContext) Reset()                    { *m = ImmutableContext{} }
func (m *ImmutableContext) String() string            { return proto.CompactTextString(m) }
func (*ImmutableContext) ProtoMessage()               {}
func (*ImmutableContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ImmutableContext) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *ImmutableContext) GetCreatorService() *auth.SignedUser {
	if m != nil {
		return m.CreatorService
	}
	return nil
}

func (m *ImmutableContext) GetUser() *auth.SignedUser {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ImmutableContext) GetSudoUser() *auth.SignedUser {
	if m != nil {
		return m.SudoUser
	}
	return nil
}

func (m *ImmutableContext) GetSession() *auth.SignedSession {
	if m != nil {
		return m.Session
	}
	return nil
}

// this may change. fields are not guaranteed to be preserved
type MutableContext struct {
	CallingService *auth.SignedUser `protobuf:"bytes,1,opt,name=CallingService" json:"CallingService,omitempty"`
	Debug          bool             `protobuf:"varint,2,opt,name=Debug" json:"Debug,omitempty"`
	Trace          bool             `protobuf:"varint,3,opt,name=Trace" json:"Trace,omitempty"`
}

func (m *MutableContext) Reset()                    { *m = MutableContext{} }
func (m *MutableContext) String() string            { return proto.CompactTextString(m) }
func (*MutableContext) ProtoMessage()               {}
func (*MutableContext) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MutableContext) GetCallingService() *auth.SignedUser {
	if m != nil {
		return m.CallingService
	}
	return nil
}

func (m *MutableContext) GetDebug() bool {
	if m != nil {
		return m.Debug
	}
	return false
}

func (m *MutableContext) GetTrace() bool {
	if m != nil {
		return m.Trace
	}
	return false
}

func init() {
	proto.RegisterType((*CallTrace)(nil), "framework.CallTrace")
	proto.RegisterType((*FrameworkMessageDetail)(nil), "framework.FrameworkMessageDetail")
	proto.RegisterType((*InContext)(nil), "framework.InContext")
	proto.RegisterType((*ImmutableContext)(nil), "framework.ImmutableContext")
	proto.RegisterType((*MutableContext)(nil), "framework.MutableContext")
}

func init() {
	proto.RegisterFile("protos/golang.conradwood.net/apis/framework/framework.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 409 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0x34, 0x29, 0xf1, 0x54, 0xaa, 0xaa, 0xa5, 0xaa, 0xcc, 0x87, 0x44, 0xb1, 0x38,
	0x54, 0x88, 0x3a, 0xa2, 0x70, 0x40, 0xe2, 0x86, 0x23, 0x24, 0x1f, 0x7c, 0xd9, 0x80, 0x38, 0x6f,
	0xe2, 0xc1, 0xb5, 0xb0, 0x77, 0xcb, 0xee, 0x3a, 0xc9, 0x13, 0xf0, 0xb6, 0xbc, 0x03, 0xf2, 0xf8,
	0x3b, 0x0a, 0xbd, 0x58, 0x9e, 0x99, 0xdf, 0x7f, 0x67, 0xfe, 0xbb, 0x03, 0x9f, 0x1f, 0xb4, 0xb2,
	0xca, 0x2c, 0x52, 0x95, 0x0b, 0x99, 0x06, 0x1b, 0x25, 0xb5, 0x48, 0x76, 0x4a, 0x25, 0x81, 0x44,
	0xbb, 0x10, 0x0f, 0x99, 0x59, 0xfc, 0xd4, 0xa2, 0xc0, 0x9d, 0xd2, 0xbf, 0xfa, 0xbf, 0x80, 0x54,
	0xcc, 0xed, 0x12, 0xcf, 0xdf, 0x3e, 0x72, 0x80, 0x28, 0xed, 0x3d, 0x7d, 0x6a, 0x99, 0xff, 0x03,
	0xdc, 0x50, 0xe4, 0xf9, 0x37, 0x2d, 0x36, 0xc8, 0x3c, 0x78, 0xb2, 0x42, 0xbd, 0xcd, 0x36, 0xe8,
	0x39, 0xd7, 0xce, 0x8d, 0xcb, 0xdb, 0x90, 0x5d, 0xc1, 0x69, 0x8c, 0xf6, 0x5e, 0x25, 0xde, 0x84,
	0x0a, 0x4d, 0x54, 0x29, 0x62, 0x34, 0x46, 0xa4, 0xe8, 0x9d, 0xd4, 0x8a, 0x26, 0xf4, 0xff, 0x38,
	0x70, 0xf5, 0xb5, 0x1d, 0xa9, 0x49, 0x2e, 0xd1, 0x8a, 0x2c, 0x67, 0x1f, 0x01, 0xba, 0x9e, 0xc6,
	0x73, 0xae, 0x4f, 0x6e, 0xce, 0xee, 0x2e, 0x83, 0xde, 0x50, 0x57, 0xe4, 0x03, 0x6e, 0xd8, 0x6a,
	0x32, 0x6a, 0xc5, 0x5e, 0x82, 0xcb, 0xf1, 0x77, 0x89, 0xc6, 0x46, 0xcb, 0x66, 0x8c, 0x3e, 0xe1,
	0x17, 0xe0, 0x46, 0x32, 0x54, 0xd2, 0xe2, 0xde, 0xb2, 0xf7, 0x30, 0x8b, 0x8a, 0xd0, 0xee, 0xc9,
	0xdf, 0xd9, 0xdd, 0x8b, 0x41, 0xd7, 0xa8, 0x28, 0x4a, 0x2b, 0xd6, 0x39, 0x36, 0x2c, 0xaf, 0x49,
	0x76, 0x0b, 0xd3, 0xb8, 0x52, 0x4c, 0x48, 0xf1, 0x6c, 0xa0, 0x88, 0xc7, 0x3c, 0x61, 0xfe, 0x5f,
	0x07, 0x2e, 0x0e, 0x8f, 0x1a, 0x4f, 0xe8, 0x1c, 0x4c, 0xc8, 0x3e, 0xc1, 0x79, 0xa8, 0x51, 0x58,
	0xa5, 0xdb, 0xdb, 0xaf, 0x7b, 0x5d, 0x04, 0xf4, 0x50, 0xab, 0x2c, 0x95, 0x98, 0x7c, 0x37, 0xa8,
	0xf9, 0x01, 0xc7, 0xde, 0xc0, 0xb4, 0xca, 0x93, 0xe9, 0x63, 0x3c, 0x55, 0xd9, 0x3b, 0x98, 0xaf,
	0xca, 0x44, 0x11, 0x39, 0xfd, 0x0f, 0xd9, 0x11, 0xec, 0xb6, 0x5a, 0x02, 0x63, 0x32, 0x25, 0xbd,
	0x19, 0xc1, 0x4f, 0x87, 0x70, 0x53, 0xe2, 0x2d, 0xe3, 0x6f, 0xe1, 0x7c, 0x7c, 0x0f, 0x64, 0x47,
	0xe4, 0x79, 0x26, 0xd3, 0xe1, 0x32, 0x1d, 0xb7, 0x33, 0xe2, 0xd8, 0x25, 0xcc, 0x96, 0xb8, 0x2e,
	0x53, 0xf2, 0x3f, 0xe7, 0x75, 0x50, 0x65, 0x69, 0x05, 0xc8, 0xe5, 0x9c, 0xd7, 0xc1, 0x97, 0xd7,
	0xf0, 0xea, 0xe8, 0x9a, 0xf7, 0xef, 0xb3, 0x3e, 0xa5, 0x15, 0xff, 0xf0, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x44, 0x3d, 0x4e, 0xbb, 0x58, 0x03, 0x00, 0x00,
}
