// Code generated by protoc-gen-go.
// source: golang.conradwood.net/apis/common/common.proto
// DO NOT EDIT!

/*
Package common is a generated protocol buffer package.

It is generated from these files:
	golang.conradwood.net/apis/common/common.proto

It has these top-level messages:
	Void
	CPULoad
	Status
	Date
*/
package common

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProgrammingLanguage int32

const (
	ProgrammingLanguage_INVALID ProgrammingLanguage = 0
	ProgrammingLanguage_GO      ProgrammingLanguage = 1
	ProgrammingLanguage_Java    ProgrammingLanguage = 2
)

var ProgrammingLanguage_name = map[int32]string{
	0: "INVALID",
	1: "GO",
	2: "Java",
}
var ProgrammingLanguage_value = map[string]int32{
	"INVALID": 0,
	"GO":      1,
	"Java":    2,
}

func (x ProgrammingLanguage) String() string {
	return proto.EnumName(ProgrammingLanguage_name, int32(x))
}
func (ProgrammingLanguage) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Language int32

const (
	Language_UNKNOWN    Language = 0
	Language_ENGLISH_UK Language = 1
	Language_GERMAN     Language = 2
)

var Language_name = map[int32]string{
	0: "UNKNOWN",
	1: "ENGLISH_UK",
	2: "GERMAN",
}
var Language_value = map[string]int32{
	"UNKNOWN":    0,
	"ENGLISH_UK": 1,
	"GERMAN":     2,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}
func (Language) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Currency int32

const (
	Currency_UNKNOWN_CURRENCY Currency = 0
	Currency_GBP              Currency = 1
	Currency_EUR              Currency = 2
	Currency_USD              Currency = 3
)

var Currency_name = map[int32]string{
	0: "UNKNOWN_CURRENCY",
	1: "GBP",
	2: "EUR",
	3: "USD",
}
var Currency_value = map[string]int32{
	"UNKNOWN_CURRENCY": 0,
	"GBP":              1,
	"EUR":              2,
	"USD":              3,
}

func (x Currency) String() string {
	return proto.EnumName(Currency_name, int32(x))
}
func (Currency) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Health int32

const (
	Health_UNKNOWN_HEALTH Health = 0
	Health_STARTING       Health = 1
	Health_READY          Health = 2
	Health_STOPPING       Health = 3
)

var Health_name = map[int32]string{
	0: "UNKNOWN_HEALTH",
	1: "STARTING",
	2: "READY",
	3: "STOPPING",
}
var Health_value = map[string]int32{
	"UNKNOWN_HEALTH": 0,
	"STARTING":       1,
	"READY":          2,
	"STOPPING":       3,
}

func (x Health) String() string {
	return proto.EnumName(Health_name, int32(x))
}
func (Health) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Void should be used when no explicit request or response is required.
type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// some services report cpuload on where they are running
// usage:
// add this to your service:
// rpc GetCPULoad(common.Void) returns (common.CPULoad);
// add this to your source:
// import (
// "golang.conradwood.net/go-easyops/linux"
// )
// add this to your grpcServer struct:
// linux.Loadavg // embed GetCPULoad() RPC
type CPULoad struct {
	Avg1     float64 `protobuf:"fixed64,1,opt,name=Avg1" json:"Avg1,omitempty"`
	Avg5     float64 `protobuf:"fixed64,2,opt,name=Avg5" json:"Avg5,omitempty"`
	Avg15    float64 `protobuf:"fixed64,3,opt,name=Avg15" json:"Avg15,omitempty"`
	CPUCount uint32  `protobuf:"varint,4,opt,name=CPUCount" json:"CPUCount,omitempty"`
	PerCPU   float64 `protobuf:"fixed64,5,opt,name=PerCPU" json:"PerCPU,omitempty"`
	User     uint64  `protobuf:"varint,6,opt,name=User" json:"User,omitempty"`
	Nice     uint64  `protobuf:"varint,7,opt,name=Nice" json:"Nice,omitempty"`
	System   uint64  `protobuf:"varint,8,opt,name=System" json:"System,omitempty"`
	Idle     uint64  `protobuf:"varint,9,opt,name=Idle" json:"Idle,omitempty"`
	IOWait   uint64  `protobuf:"varint,10,opt,name=IOWait" json:"IOWait,omitempty"`
	IRQ      uint64  `protobuf:"varint,11,opt,name=IRQ" json:"IRQ,omitempty"`
	SoftIRQ  uint64  `protobuf:"varint,12,opt,name=SoftIRQ" json:"SoftIRQ,omitempty"`
	Sum      uint64  `protobuf:"varint,13,opt,name=Sum" json:"Sum,omitempty"`
	RawSum   uint64  `protobuf:"varint,14,opt,name=RawSum" json:"RawSum,omitempty"`
	IdleTime float64 `protobuf:"fixed64,15,opt,name=IdleTime" json:"IdleTime,omitempty"`
}

func (m *CPULoad) Reset()                    { *m = CPULoad{} }
func (m *CPULoad) String() string            { return proto.CompactTextString(m) }
func (*CPULoad) ProtoMessage()               {}
func (*CPULoad) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CPULoad) GetAvg1() float64 {
	if m != nil {
		return m.Avg1
	}
	return 0
}

func (m *CPULoad) GetAvg5() float64 {
	if m != nil {
		return m.Avg5
	}
	return 0
}

func (m *CPULoad) GetAvg15() float64 {
	if m != nil {
		return m.Avg15
	}
	return 0
}

func (m *CPULoad) GetCPUCount() uint32 {
	if m != nil {
		return m.CPUCount
	}
	return 0
}

func (m *CPULoad) GetPerCPU() float64 {
	if m != nil {
		return m.PerCPU
	}
	return 0
}

func (m *CPULoad) GetUser() uint64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *CPULoad) GetNice() uint64 {
	if m != nil {
		return m.Nice
	}
	return 0
}

func (m *CPULoad) GetSystem() uint64 {
	if m != nil {
		return m.System
	}
	return 0
}

func (m *CPULoad) GetIdle() uint64 {
	if m != nil {
		return m.Idle
	}
	return 0
}

func (m *CPULoad) GetIOWait() uint64 {
	if m != nil {
		return m.IOWait
	}
	return 0
}

func (m *CPULoad) GetIRQ() uint64 {
	if m != nil {
		return m.IRQ
	}
	return 0
}

func (m *CPULoad) GetSoftIRQ() uint64 {
	if m != nil {
		return m.SoftIRQ
	}
	return 0
}

func (m *CPULoad) GetSum() uint64 {
	if m != nil {
		return m.Sum
	}
	return 0
}

func (m *CPULoad) GetRawSum() uint64 {
	if m != nil {
		return m.RawSum
	}
	return 0
}

func (m *CPULoad) GetIdleTime() float64 {
	if m != nil {
		return m.IdleTime
	}
	return 0
}

// Status represents whether or not the specified operation
// was successful, and what error occurred if it was not.
type Status struct {
	// Success is set to true or false depending on whether or
	// not the operation was successful.
	// In the event of an error, further details can be found
	// in the `ErrorCode` and `ErrorDescription` fields.
	Success bool `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	// ErrorCode is present if an error has occurred during the
	// operation. ErrorCode mappings will be listed in our
	// documentation.
	ErrorCode int32 `protobuf:"varint,2,opt,name=ErrorCode" json:"ErrorCode,omitempty"`
	// ErrorDescription is present if an error has occurred during
	// the operation. This is intended to be human-readable (machines
	// should use the ErrorCode instead).
	ErrorDescription string `protobuf:"bytes,3,opt,name=ErrorDescription" json:"ErrorDescription,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Status) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Status) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Status) GetErrorDescription() string {
	if m != nil {
		return m.ErrorDescription
	}
	return ""
}

type Date struct {
	Day   uint32 `protobuf:"varint,1,opt,name=Day" json:"Day,omitempty"`
	Month uint32 `protobuf:"varint,2,opt,name=Month" json:"Month,omitempty"`
	Year  uint32 `protobuf:"varint,3,opt,name=Year" json:"Year,omitempty"`
}

func (m *Date) Reset()                    { *m = Date{} }
func (m *Date) String() string            { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()               {}
func (*Date) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Date) GetDay() uint32 {
	if m != nil {
		return m.Day
	}
	return 0
}

func (m *Date) GetMonth() uint32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetYear() uint32 {
	if m != nil {
		return m.Year
	}
	return 0
}

var E_SqlType = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51235,
	Name:          "common.sql_type",
	Tag:           "bytes,51235,opt,name=sql_type,json=sqlType",
	Filename:      "golang.conradwood.net/apis/common/common.proto",
}

var E_SqlReference = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51236,
	Name:          "common.sql_reference",
	Tag:           "bytes,51236,opt,name=sql_reference,json=sqlReference",
	Filename:      "golang.conradwood.net/apis/common/common.proto",
}

var E_SqlUnique = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51237,
	Name:          "common.sql_unique",
	Tag:           "bytes,51237,opt,name=sql_unique,json=sqlUnique",
	Filename:      "golang.conradwood.net/apis/common/common.proto",
}

var E_SqlIgnore = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51238,
	Name:          "common.sql_ignore",
	Tag:           "bytes,51238,opt,name=sql_ignore,json=sqlIgnore",
	Filename:      "golang.conradwood.net/apis/common/common.proto",
}

var E_SqlName = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51239,
	Name:          "common.sql_name",
	Tag:           "bytes,51239,opt,name=sql_name,json=sqlName",
	Filename:      "golang.conradwood.net/apis/common/common.proto",
}

var E_SqlNullreference = &proto.ExtensionDesc{
	ExtendedType:  (*google_protobuf.FieldOptions)(nil),
	ExtensionType: (*string)(nil),
	Field:         51240,
	Name:          "common.sql_nullreference",
	Tag:           "bytes,51240,opt,name=sql_nullreference,json=sqlNullreference",
	Filename:      "golang.conradwood.net/apis/common/common.proto",
}

func init() {
	proto.RegisterType((*Void)(nil), "common.Void")
	proto.RegisterType((*CPULoad)(nil), "common.CPULoad")
	proto.RegisterType((*Status)(nil), "common.Status")
	proto.RegisterType((*Date)(nil), "common.Date")
	proto.RegisterEnum("common.ProgrammingLanguage", ProgrammingLanguage_name, ProgrammingLanguage_value)
	proto.RegisterEnum("common.Language", Language_name, Language_value)
	proto.RegisterEnum("common.Currency", Currency_name, Currency_value)
	proto.RegisterEnum("common.Health", Health_name, Health_value)
	proto.RegisterExtension(E_SqlType)
	proto.RegisterExtension(E_SqlReference)
	proto.RegisterExtension(E_SqlUnique)
	proto.RegisterExtension(E_SqlIgnore)
	proto.RegisterExtension(E_SqlName)
	proto.RegisterExtension(E_SqlNullreference)
}

func init() { proto.RegisterFile("golang.conradwood.net/apis/common/common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xdd, 0x6e, 0xa3, 0x46,
	0x18, 0x35, 0xfe, 0xc1, 0xf8, 0xdb, 0x38, 0x9d, 0x4e, 0xab, 0x0a, 0xad, 0x5a, 0xc9, 0xeb, 0xab,
	0xc8, 0x17, 0x58, 0xd5, 0x36, 0x37, 0xae, 0x54, 0xc9, 0xc1, 0x5e, 0x9b, 0xae, 0x17, 0xd3, 0xc1,
	0x6c, 0x94, 0xde, 0x44, 0x13, 0x33, 0xa1, 0x48, 0xc0, 0xd8, 0x03, 0x24, 0xf2, 0x5b, 0xf4, 0x1d,
	0xfa, 0xfb, 0x4a, 0x7d, 0x9b, 0x6a, 0x06, 0x9c, 0x5a, 0xea, 0x85, 0xf7, 0x8a, 0x73, 0xce, 0x7c,
	0xe7, 0x0c, 0x73, 0x10, 0x03, 0x56, 0xc4, 0x13, 0x9a, 0x45, 0xd6, 0x96, 0x67, 0x82, 0x86, 0xcf,
	0x9c, 0x87, 0x56, 0xc6, 0x8a, 0x31, 0xdd, 0xc5, 0xf9, 0x78, 0xcb, 0xd3, 0x94, 0x67, 0xf5, 0xc3,
	0xda, 0x09, 0x5e, 0x70, 0xac, 0x57, 0xec, 0xf5, 0x20, 0xe2, 0x3c, 0x4a, 0xd8, 0x58, 0xa9, 0x0f,
	0xe5, 0xe3, 0x38, 0x64, 0xf9, 0x56, 0xc4, 0xbb, 0x82, 0x8b, 0x6a, 0x72, 0xa8, 0x43, 0xfb, 0x23,
	0x8f, 0xc3, 0xe1, 0x3f, 0x4d, 0xe8, 0xda, 0x5e, 0xb0, 0xe2, 0x34, 0xc4, 0x18, 0xda, 0xd3, 0xa7,
	0xe8, 0x5b, 0x53, 0x1b, 0x68, 0x57, 0x1a, 0x51, 0xb8, 0xd6, 0xae, 0xcd, 0xe6, 0x8b, 0x76, 0x8d,
	0xbf, 0x84, 0x8e, 0x5c, 0xbb, 0x36, 0x5b, 0x4a, 0xac, 0x08, 0x7e, 0x0d, 0x86, 0xed, 0x05, 0x36,
	0x2f, 0xb3, 0xc2, 0x6c, 0x0f, 0xb4, 0xab, 0x3e, 0x79, 0xe1, 0xf8, 0x2b, 0xd0, 0x3d, 0x26, 0x6c,
	0x2f, 0x30, 0x3b, 0xca, 0x52, 0x33, 0x99, 0x1e, 0xe4, 0x4c, 0x98, 0xfa, 0x40, 0xbb, 0x6a, 0x13,
	0x85, 0xa5, 0xe6, 0xc6, 0x5b, 0x66, 0x76, 0x2b, 0x4d, 0x62, 0xe9, 0xf7, 0x0f, 0x79, 0xc1, 0x52,
	0xd3, 0x50, 0x6a, 0xcd, 0xe4, 0xac, 0x13, 0x26, 0xcc, 0xec, 0x55, 0xb3, 0x12, 0xcb, 0x59, 0x67,
	0x7d, 0x4b, 0xe3, 0xc2, 0x84, 0x6a, 0xb6, 0x62, 0x18, 0x41, 0xcb, 0x21, 0x3f, 0x99, 0xaf, 0x94,
	0x28, 0x21, 0x36, 0xa1, 0xeb, 0xf3, 0xc7, 0x42, 0xaa, 0x17, 0x4a, 0x3d, 0x52, 0x39, 0xeb, 0x97,
	0xa9, 0xd9, 0xaf, 0x66, 0xfd, 0x32, 0x95, 0xa9, 0x84, 0x3e, 0x4b, 0xf1, 0xb2, 0x4a, 0xad, 0x98,
	0x3c, 0xb5, 0xdc, 0x75, 0x13, 0xa7, 0xcc, 0xfc, 0x4c, 0x9d, 0xed, 0x85, 0x0f, 0x13, 0xd0, 0xfd,
	0x82, 0x16, 0x65, 0xae, 0x76, 0x2a, 0xb7, 0x5b, 0x96, 0xe7, 0xaa, 0x5c, 0x83, 0x1c, 0x29, 0xfe,
	0x1a, 0x7a, 0x73, 0x21, 0xb8, 0xb0, 0x79, 0xc8, 0x54, 0xc9, 0x1d, 0xf2, 0x9f, 0x80, 0x47, 0x80,
	0x14, 0x99, 0xd5, 0x9f, 0x2f, 0xe6, 0x99, 0x2a, 0xbd, 0x47, 0xfe, 0xa7, 0x0f, 0x6f, 0xa0, 0x3d,
	0xa3, 0x05, 0x93, 0xef, 0x3e, 0xa3, 0x07, 0xb5, 0x4f, 0x9f, 0x48, 0x28, 0xbf, 0xd7, 0x07, 0x9e,
	0x15, 0xbf, 0xa8, 0xfc, 0x3e, 0xa9, 0x88, 0xec, 0xee, 0x8e, 0x51, 0xa1, 0xf2, 0xfa, 0x44, 0xe1,
	0xd1, 0x77, 0xf0, 0x85, 0x27, 0x78, 0x24, 0x68, 0x9a, 0xc6, 0x59, 0xb4, 0xa2, 0x59, 0x54, 0xd2,
	0x88, 0xe1, 0x57, 0xd0, 0x75, 0xdc, 0x8f, 0xd3, 0x95, 0x33, 0x43, 0x0d, 0xac, 0x43, 0x73, 0xb1,
	0x46, 0x1a, 0x36, 0xa0, 0xfd, 0x23, 0x7d, 0xa2, 0xa8, 0x39, 0x7a, 0x0b, 0xc6, 0xe9, 0x68, 0xe0,
	0xbe, 0x77, 0xd7, 0xb7, 0x2e, 0x6a, 0xe0, 0x4b, 0x80, 0xb9, 0xbb, 0x58, 0x39, 0xfe, 0xf2, 0x3e,
	0x78, 0x8f, 0x34, 0x0c, 0xa0, 0x2f, 0xe6, 0xe4, 0xc3, 0xd4, 0x45, 0xcd, 0xd1, 0xf7, 0x60, 0xd8,
	0xa5, 0x10, 0x2c, 0xdb, 0xca, 0x17, 0x44, 0xb5, 0xe9, 0xde, 0x0e, 0x08, 0x99, 0xbb, 0xf6, 0x1d,
	0x6a, 0xe0, 0x2e, 0xb4, 0x16, 0x37, 0x1e, 0xd2, 0x24, 0x98, 0x07, 0x04, 0x35, 0x25, 0x08, 0xfc,
	0x19, 0x6a, 0x8d, 0x6c, 0xd0, 0x97, 0x8c, 0x26, 0xea, 0x14, 0x97, 0x47, 0xeb, 0x72, 0x3e, 0x5d,
	0x6d, 0x96, 0xa8, 0x81, 0x2f, 0xc0, 0xf0, 0x37, 0x53, 0xb2, 0x71, 0xdc, 0x05, 0xd2, 0x70, 0x0f,
	0x3a, 0x64, 0x3e, 0x9d, 0xdd, 0xa1, 0x66, 0xb5, 0xb0, 0xf6, 0x3c, 0xb9, 0xd0, 0x9a, 0x4c, 0xc0,
	0xc8, 0xf7, 0xc9, 0x7d, 0x71, 0xd8, 0x31, 0xfc, 0x8d, 0x55, 0xfd, 0x31, 0xd6, 0xf1, 0x8f, 0xb1,
	0xde, 0xc5, 0x2c, 0x09, 0xd7, 0xaa, 0xda, 0xdc, 0xfc, 0xed, 0xd7, 0xaa, 0xf5, 0x6e, 0xbe, 0x4f,
	0x36, 0x87, 0x1d, 0x9b, 0xcc, 0xa0, 0x2f, 0xbd, 0x82, 0x3d, 0x32, 0x79, 0x84, 0xb3, 0x01, 0xbf,
	0xd7, 0x01, 0x17, 0xf9, 0x3e, 0x21, 0x47, 0xd3, 0xe4, 0x07, 0x00, 0x99, 0x52, 0x66, 0xf1, 0xbe,
	0x3c, 0x1b, 0xf1, 0x47, 0x1d, 0xd1, 0xcb, 0xf7, 0x49, 0xa0, 0x1c, 0x47, 0x7f, 0x1c, 0x65, 0x5c,
	0x9c, 0xf5, 0xff, 0x79, 0xe2, 0x77, 0x94, 0xe3, 0xd8, 0x40, 0x46, 0xd3, 0xb3, 0xee, 0xbf, 0x4e,
	0x1a, 0x70, 0x69, 0xca, 0x26, 0x2b, 0xf8, 0x5c, 0x79, 0xcb, 0x24, 0xf9, 0xe4, 0x16, 0xfe, 0xae,
	0x43, 0x90, 0x0c, 0x39, 0x35, 0xde, 0xbc, 0x83, 0x37, 0x19, 0x2b, 0x4e, 0xef, 0xb9, 0xfa, 0xe6,
	0x93, 0x57, 0x9d, 0x55, 0xdd, 0x6a, 0x3f, 0xbf, 0x39, 0x7b, 0x1b, 0x3e, 0xe8, 0x6a, 0xe3, 0xb7,
	0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x30, 0x32, 0xdf, 0x39, 0x05, 0x00, 0x00,
}
