package client

import (
	"context"
	"fmt"
	pp "golang.conradwood.net/go-easyops/profiling"
	"golang.conradwood.net/go-easyops/prometheus"
	"golang.conradwood.net/go-easyops/rpc"
	//	"reflect"
	//"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"
	"time"
)

// called for each outbound rpc
func ClientMetricsUnaryInterceptor(ctx context.Context, method string, req, reply interface{}, cc *grpc.ClientConn, invoker grpc.UnaryInvoker, opts ...grpc.CallOption) error {
	if ctx == nil {
		panic("missing context")
	}
	pp.ClientRpcEntered()
	defer pp.ClientRpcDone()
	start := time.Now()
	s, m, err := splitMethodAndService(method)
	// keep prometheus happy: (not to panic)
	if s == "" {
		s = "unknown"
	}
	if m == "" {
		m = "unknown"
	}
	// bad programmer! - log it prominently (often)
	if err != nil {
		fmt.Printf("[go-easyops] invalid fqdn method: \"%s\": %s\n", method, err)
	}
	cs := rpc.CallStateFromContext(ctx)
	if cs == nil {
		if *dialer_debug || *debug_rpc_client {
			fmt.Printf("[go-easyops] WARNING - calling external method %s.%s() without callstate\n", s, m)
		}
	} else {
		if !isKnownNotAuthRPCs(s, m) {
			_, ex := metadata.FromOutgoingContext(ctx)
			if !ex {
				fmt.Printf("[go-easyops] WARNING - calling external method %s.%s without metadata (authentication)\n", s, m)
			}
		}
	}
	if *dialer_debug || *debug_rpc_client {
		//		cs.PrintContext()
		us := "none"
		if cs.User() != nil {
			us = fmt.Sprintf("UserID=%s, Email=%s", cs.User().ID, cs.User().Email)
		}
		fmt.Printf("Invoking method %s.%s as %s...\n", s, m, us)
		//fmt.Printf("Contype: %s (%T)\n", reflect.TypeOf(cc), cc)
		//		fmt.Printf("Ctx: %#v\n", ctx)
	}
	grpc_client_sent.With(prometheus.Labels{"method": m, "servicename": s}).Inc()

	// generated by gRPC, calls the gRPC method
	err = invoker(ctx, method, req, reply, cc, opts...)

	observeRPC(start, s, m) // record time.Since(start) into metric

	dur := time.Since(start)
	if err != nil {
		grpc_client_failed.With(prometheus.Labels{"method": m, "servicename": s}).Inc()
		if *dialer_debug || *debug_rpc_client {
			fmt.Printf("Invoked remote method=%s duration=%0.2fs error=%v (Method: \"%s\" in Service: \"%s\")\n", method, dur.Seconds(), err, m, s)
		}
	} else if *debug_rpc_client {
		fmt.Printf("Invoked method %s.%s (%0.2fs)...\n", s, m, dur.Seconds())
	}

	return err
}
